name: seventh_player
description: A Flutter video player project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  chewie: ^1.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  get_it: ^7.2.0
  http: ^0.13.5
  intl: ^0.17.0
  mobx: ^2.1.4
  shared_preferences: ^2.0.18
  video_player: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  flutter_launcher_icons: ^0.12.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/image/
    - assets/icon/
