name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  flutter_test:
    name: Run Flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format --dry-run --set-exit-if-changed lib/
      - run: flutter format --dry-run --set-exit-if-changed test/
      - run: flutter test --coverage
      - uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 80
